// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-boHRFWRHxGAU_3NGGTpQXwbsGvVQTcM',
    appId: '1:79098376241:web:047efd3f8f60caa1f62510',
    messagingSenderId: '79098376241',
    projectId: 'dice-game-f15b9',
    authDomain: 'dice-game-f15b9.firebaseapp.com',
    storageBucket: 'dice-game-f15b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwgurFCUMBseIxWbQ05HCXWyr0TUPehxQ',
    appId: '1:79098376241:android:fe4b7933803fd538f62510',
    messagingSenderId: '79098376241',
    projectId: 'dice-game-f15b9',
    storageBucket: 'dice-game-f15b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLck38YwIjy1aLy_XgS4PboMuoawIuf-A',
    appId: '1:79098376241:ios:c070ccd3190e4d60f62510',
    messagingSenderId: '79098376241',
    projectId: 'dice-game-f15b9',
    storageBucket: 'dice-game-f15b9.appspot.com',
    iosClientId: '79098376241-9dheucr6j0555d4bpuu7u47uvobf4i38.apps.googleusercontent.com',
    iosBundleId: 'com.example.fapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLck38YwIjy1aLy_XgS4PboMuoawIuf-A',
    appId: '1:79098376241:ios:268ad8b3f7e06b39f62510',
    messagingSenderId: '79098376241',
    projectId: 'dice-game-f15b9',
    storageBucket: 'dice-game-f15b9.appspot.com',
    iosClientId: '79098376241-053d6dsnolodr4v7sj8njegthup0tkqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.fapp.RunnerTests',
  );
}
